
secondaryInstrumentIddasdas
dasdas
dasdasasdas
dasdasasdasda
secondaryInstrumentIddasdasasd
assetIdas
dasdasasdasdadas
dasdasasdasdadasasd
assetIdasdas
dasdasasdasdadasasdsd
assetIdqs
dfgw
fgdf
g
sd
fgs
dgs
dfg
sdf
g
sdf
gsdf
gsdfdfg

    totalAmount: 901,
    openingAmount: null,
    closingAmount: null,
    serviceProviderReferenceNumber: null,
    userTransactionNumber: null,
    bankName: null,
    bankAccountNumber: null,
    remark: null,
    id: 8300,
    isActive: true,
    createdDate: 2018-10-30T08:36:03.000Z,
    lastModifiedDate: 2018-10-30T08:36:03.000Z,
    fk_id_order_item: null,
    fk_id_instrument: 61107,
    fk_id_secondary_instrument: null,
    fk_id_account: 59,
    fk_id_service_provider_account: 217,
    fk_id_currency: 1,
    fk_id_transaction_type: 3,
    fk_id_goal: 36,
    statusLabel: 'Successful',
    transactionSubTypeLabel: 'Normal',
    orderItemId: null,
    transactionTypeId: 3,
    instrumentId: 61107,
    secondaryInstrumentId: null,
    accountId: 59,
    serviceProviderAccountId: 217,
    currencyId: 1,
    goalId: 36,
    instrument: { name: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       fullName: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       description: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       serviceProviderSpecificCode: '153GZ',
       rtaCode: '153GZ',
       bosCode: null,
       nseCode: null,
       bseCode: 'BS153GZ-GR',
       bseUniqueId: '9979',
       isinCode: 'INF209K01VA3',
       fundooCode: '3791',
       fundooRTACode: 'B153GZ',
       instrumentStatus: 1,
       inceptionPrice: 183.9707,
       inceptionPriceDate: 2012-12-30T18:30:00.000Z,
       lastPrice: 291.3048,
       lastPriceDate: 2018-10-30T18:30:00.000Z,
       movementFromPreviousPrice: null,
       percentageMovementFromPreviousPrice: null,
       isPrimary: true,
       isRecommended: false,
       id: 61107,
       isActive: true,
       createdDate: 2018-10-30T05:13:58.000Z,
       lastModifiedDate: 2018-11-01T05:55:55.000Z,
       fk_id_product: 5,
       fk_id_asset: 4,
       fk_id_tax_asset: 5,
       fk_id_instrument_type: null,
       fk_id_instrument_category: 22,
       fk_id_capital_bucket: null,
       fk_id_service_provider: 10,
       fk_id_asset_classification: null,
       instrumentStatusLabel: 'Active',
       productId: 5,
       assetId: 4,
       assetClassificationId: null,
       taxAssetId: 5,
       instrumentTypeId: null,
       instrumentCategoryId: 22,
       capitalBucketId: null,
       serviceProviderId: 10,
       dailyInstrumentPriceSnapshots: [Array] },
    transactionType: { name: 'Partial Redemption',
       description: null,
       bosCode: null,
       nseCode: null,
       bseCode: null,
       holdingCalculationBuySellType: 2,
       id: 3,
       isActive: true,
       createdDate: 2018-10-30T04:53:17.000Z,
       lastModifiedDate: 2018-10-30T04:53:17.000Z,
       holdingCalculationBuySellTypeLabel: 'Sell' } },
  { isDummy: false,
    reverseFeedUniqueHash: null,
    bosCode: null,
    nseCode: null,
    bseCode: null,
    transactionDate: 2018-11-26T18:30:00.000Z,
    orderDate: null,
    status: 3,
    transactionSubType: 1,
    quantity: 0.391,
    openingQuantity: null,
    closingQuantity: null,
    pricePerUnit: 255.568,
    totalAmount: 100,
    openingAmount: null,
    closingAmount: null,
    serviceProviderReferenceNumber: null,
    userTransactionNumber: null,
    bankName: null,
    bankAccountNumber: null,
    remark: null,
    id: 8299,
    isActive: true,
    createdDate: 2018-10-30T08:36:03.000Z,
    lastModifiedDate: 2018-10-30T08:36:03.000Z,
    fk_id_order_item: null,
    fk_id_instrument: 61107,
    fk_id_secondary_instrument: null,
    fk_id_account: 59,
    fk_id_service_provider_account: 217,
    fk_id_currency: 1,
    fk_id_transaction_type: 3,
    fk_id_goal: 36,
    statusLabel: 'Successful',
    transactionSubTypeLabel: 'Normal',
    orderItemId: null,
    transactionTypeId: 3,
    instrumentId: 61107,
    secondaryInstrumentId: null,
    accountId: 59,
    serviceProviderAccountId: 217,
    currencyId: 1,
    goalId: 36,
    instrument: { name: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       fullName: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       description: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       serviceProviderSpecificCode: '153GZ',
       rtaCode: '153GZ',
       bosCode: null,
       nseCode: null,
       bseCode: 'BS153GZ-GR',
       bseUniqueId: '9979',
       isinCode: 'INF209K01VA3',
       fundooCode: '3791',
       fundooRTACode: 'B153GZ',
       instrumentStatus: 1,
       inceptionPrice: 183.9707,
       inceptionPriceDate: 2012-12-30T18:30:00.000Z,
       lastPrice: 291.3048,
       lastPriceDate: 2018-10-30T18:30:00.000Z,
       movementFromPreviousPrice: null,
       percentageMovementFromPreviousPrice: null,
       isPrimary: true,
       isRecommended: false,
       id: 61107,
       isActive: true,
       createdDate: 2018-10-30T05:13:58.000Z,
       lastModifiedDate: 2018-11-01T05:55:55.000Z,
       fk_id_product: 5,
       fk_id_asset: 4,
       fk_id_tax_asset: 5,
       fk_id_instrument_type: null,
       fk_id_instrument_category: 22,
       fk_id_capital_bucket: null,
       fk_id_service_provider: 10,
       fk_id_asset_classification: null,
       instrumentStatusLabel: 'Active',
       productId: 5,
       assetId: 4,
       assetClassificationId: null,
       taxAssetId: 5,
       instrumentTypeId: null,
       instrumentCategoryId: 22,
       capitalBucketId: null,
       serviceProviderId: 10,
       dailyInstrumentPriceSnapshots: [Array] },
    transactionType: { name: 'Partial Redemption',
       description: null,
       bosCode: null,
       nseCode: null,
       bseCode: null,
       holdingCalculationBuySellType: 2,
       id: 3,
       isActive: true,
       createdDate: 2018-10-30T04:53:17.000Z,
       lastModifiedDate: 2018-10-30T04:53:17.000Z,
       holdingCalculationBuySellTypeLabel: 'Sell' } },
  { isDummy: false,
    reverseFeedUniqueHash: null,
    bosCode: null,
    nseCode: null,
    bseCode: null,
    transactionDate: 2018-11-21T18:30:00.000Z,
    orderDate: null,
    status: 3,
    transactionSubType: 1,
    quantity: 3.916,
    openingQuantity: null,
    closingQuantity: null,
    pricePerUnit: 255.339,
    totalAmount: 1000,
    openingAmount: null,
    closingAmount: null,
    serviceProviderReferenceNumber: null,
    userTransactionNumber: null,
    bankName: null,
    bankAccountNumber: null,
    remark: null,
    id: 8298,
    isActive: true,
    createdDate: 2018-10-30T08:36:03.000Z,
    lastModifiedDate: 2018-10-30T08:36:03.000Z,
    fk_id_order_item: null,
    fk_id_instrument: 61107,
    fk_id_secondary_instrument: null,
    fk_id_account: 59,
    fk_id_service_provider_account: 217,
    fk_id_currency: 1,
    fk_id_transaction_type: 1,
    fk_id_goal: 36,
    statusLabel: 'Successful',
    transactionSubTypeLabel: 'Normal',
    orderItemId: null,
    transactionTypeId: 1,
    instrumentId: 61107,
    secondaryInstrumentId: null,
    accountId: 59,
    serviceProviderAccountId: 217,
    currencyId: 1,
    goalId: 36,
    instrument: { name: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       fullName: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       description: 'ADITYA BIRLA SUN LIFE LIQUID FUND DIRECT PLAN - GROWTH',
       serviceProviderSpecificCode: '153GZ',
       rtaCode: '153GZ',
       bosCode: null,
       nseCode: null,
       bseCode: 'BS153GZ-GR',
       bseUniqueId: '9979',
       isinCode: 'INF209K01VA3',
       fundooCode: '3791',
       fundooRTACode: 'B153GZ',
       instrumentStatus: 1,
       inceptionPrice: 183.9707,
       inceptionPriceDate: 2012-12-30T18:30:00.000Z,
       lastPrice: 291.3048,
       lastPriceDate: 2018-10-30T18:30:00.000Z,
       movementFromPreviousPrice: null,
       percentageMovementFromPreviousPrice: null,
       isPrimary: true,
       isRecommended: false,
       id: 61107,
       isActive: true,
       createdDate: 2018-10-30T05:13:58.000Z,
       lastModifiedDate: 2018-11-01T05:55:55.000Z,
       fk_id_product: 5,
       fk_id_asset: 4,
       fk_id_tax_asset: 5,
       fk_id_instrument_type: null,
       fk_id_instrument_category: 22,
       fk_id_capital_bucket: null,
       fk_id_service_provider: 10,
       fk_id_asset_classification: null,
       instrumentStatusLabel: 'Active',
       productId: 5,
       assetId: 4,
       assetClassificationId: null,
       taxAssetId: 5,
       instrumentTypeId: null,
       instrumentCategoryId: 22,
       capitalBucketId: null,
       serviceProviderId: 10,
       dailyInstrumentPriceSnapshots: [Array] },
    transactionType: { name: 'Fresh Purchase',
       description: null,
       bosCode: null,
       nseCode: null,
       bseCode: null,
       holdingCalculationBuySellType: 1,
       id: 1,
       isActive: true,
       createdDate: 2018-10-30T04:53:17.000Z,
       lastModifiedDate: 2018-10-30T04:53:17.000Z,
       holdingCalculationBuySellTypeLabel: 'Buy' } }
